import {
  pgTable,
  bigserial,
  bigint,
  varchar,
  text,
  boolean,
  timestamp,
  numeric,
  date,
  integer,
} from "drizzle-orm/pg-core";
import { agencies, customers, suppliers, airlines, consultants, countries, cities } from "./schema-core";
import { vouchers } from "./schema-accounting";

export const tickets = pgTable("tickets", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  agencyId: bigint("agency_id", { mode: "number" }).notNull().references(() => agencies.id, { onDelete: "cascade" }),
  voucherId: bigint("voucher_id", { mode: "number" }).notNull().unique().references(() => vouchers.id, { onDelete: "cascade" }),
  customerId: bigint("customer_id", { mode: "number" }).references(() => customers.id),
  supplierId: bigint("supplier_id", { mode: "number" }).references(() => suppliers.id),
  airlineId: bigint("airline_id", { mode: "number" }).references(() => airlines.id),
  consultantId: bigint("consultant_id", { mode: "number" }).references(() => consultants.id),
  pnr: varchar("pnr", { length: 50 }),
  ticketNo: varchar("ticket_no", { length: 80 }),
  passengerName: varchar("passenger_name", { length: 200 }),
  sectorFrom: varchar("sector_from", { length: 100 }),
  sectorTo: varchar("sector_to", { length: 100 }),
  issueDate: date("issue_date"),
  travelDate: date("travel_date"),
  baseFare: numeric("base_fare", { precision: 18, scale: 2 }).notNull().default("0"),
  taxAmount: numeric("tax_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  serviceCharge: numeric("service_charge", { precision: 18, scale: 2 }).notNull().default("0"),
  commissionAmount: numeric("commission_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  saleAmount: numeric("sale_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  purchaseAmount: numeric("purchase_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  profitAmount: numeric("profit_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  isBsp: boolean("is_bsp").notNull().default(false),
  status: varchar("status", { length: 20 }).notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const visas = pgTable("visas", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  agencyId: bigint("agency_id", { mode: "number" }).notNull().references(() => agencies.id, { onDelete: "cascade" }),
  voucherId: bigint("voucher_id", { mode: "number" }).notNull().unique().references(() => vouchers.id, { onDelete: "cascade" }),
  customerId: bigint("customer_id", { mode: "number" }).references(() => customers.id),
  supplierId: bigint("supplier_id", { mode: "number" }).references(() => suppliers.id),
  consultantId: bigint("consultant_id", { mode: "number" }).references(() => consultants.id),
  visaType: varchar("visa_type", { length: 100 }),
  visaNo: varchar("visa_no", { length: 100 }),
  passportNo: varchar("passport_no", { length: 100 }),
  countryId: bigint("country_id", { mode: "number" }).references(() => countries.id),
  issueDate: date("issue_date"),
  sellingAmount: numeric("selling_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  purchaseAmount: numeric("purchase_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  exchangeRate: numeric("exchange_rate", { precision: 18, scale: 6 }).notNull().default("1"),
  profitAmount: numeric("profit_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  status: varchar("status", { length: 20 }).notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const hotels = pgTable("hotels", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  agencyId: bigint("agency_id", { mode: "number" }).notNull().references(() => agencies.id, { onDelete: "cascade" }),
  voucherId: bigint("voucher_id", { mode: "number" }).notNull().unique().references(() => vouchers.id, { onDelete: "cascade" }),
  customerId: bigint("customer_id", { mode: "number" }).references(() => customers.id),
  supplierId: bigint("supplier_id", { mode: "number" }).references(() => suppliers.id),
  consultantId: bigint("consultant_id", { mode: "number" }).references(() => consultants.id),
  hotelName: varchar("hotel_name", { length: 200 }),
  countryId: bigint("country_id", { mode: "number" }).references(() => countries.id),
  cityId: bigint("city_id", { mode: "number" }).references(() => cities.id),
  checkInDate: date("check_in_date"),
  checkOutDate: date("check_out_date"),
  nights: integer("nights"),
  rooms: integer("rooms"),
  adults: integer("adults"),
  children: integer("children"),
  roomType: varchar("room_type", { length: 100 }),
  sellingAmount: numeric("selling_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  purchaseAmount: numeric("purchase_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  profitAmount: numeric("profit_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  status: varchar("status", { length: 20 }).notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const refunds = pgTable("refunds", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  agencyId: bigint("agency_id", { mode: "number" }).notNull().references(() => agencies.id, { onDelete: "cascade" }),
  voucherId: bigint("voucher_id", { mode: "number" }).notNull().unique().references(() => vouchers.id, { onDelete: "cascade" }),
  relatedVoucherId: bigint("related_voucher_id", { mode: "number" }).references(() => vouchers.id),
  refundDate: date("refund_date").notNull(),
  reason: text("reason"),
  amount: numeric("amount", { precision: 18, scale: 2 }).notNull().default("0"),
  currencyId: bigint("currency_id", { mode: "number" }),
  status: varchar("status", { length: 20 }).notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const packages = pgTable("packages", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  agencyId: bigint("agency_id", { mode: "number" }).notNull().references(() => agencies.id, { onDelete: "cascade" }),
  voucherId: bigint("voucher_id", { mode: "number" }).notNull().unique().references(() => vouchers.id, { onDelete: "cascade" }),
  customerId: bigint("customer_id", { mode: "number" }).references(() => customers.id),
  packageName: varchar("package_name", { length: 200 }).notNull(),
  destination: varchar("destination", { length: 200 }),
  startDate: date("start_date"),
  endDate: date("end_date"),
  totalSaleAmount: numeric("total_sale_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  totalPurchaseAmount: numeric("total_purchase_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  totalProfit: numeric("total_profit", { precision: 18, scale: 2 }).notNull().default("0"),
  status: varchar("status", { length: 20 }).notNull().default("active"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const packageItems = pgTable("package_items", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  packageId: bigint("package_id", { mode: "number" }).notNull().references(() => packages.id, { onDelete: "cascade" }),
  itemType: varchar("item_type", { length: 50 }).notNull(),
  referenceId: bigint("reference_id", { mode: "number" }),
  description: text("description"),
  amount: numeric("amount", { precision: 18, scale: 2 }).notNull().default("0"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const bspSales = pgTable("bsp_sales", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  agencyId: bigint("agency_id", { mode: "number" }).notNull().references(() => agencies.id, { onDelete: "cascade" }),
  ticketId: bigint("ticket_id", { mode: "number" }).notNull().references(() => tickets.id, { onDelete: "cascade" }),
  bspPeriod: varchar("bsp_period", { length: 20 }).notNull(),
  airlineId: bigint("airline_id", { mode: "number" }).references(() => airlines.id),
  grossAmount: numeric("gross_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  commissionAmount: numeric("commission_amount", { precision: 18, scale: 2 }).notNull().default("0"),
  netRemittance: numeric("net_remittance", { precision: 18, scale: 2 }).notNull().default("0"),
  settlementStatus: varchar("settlement_status", { length: 20 }).notNull().default("pending"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
